### PR TITLE
[AB2D-6077] Code Smells

### PR DESCRIPTION
**Pull request by Rwolfe-Nava**
## 🎫 Ticket

https://jira.cms.gov/browse/AB2D-5907
https://jira.cms.gov/browse/AB2D-6040
https://jira.cms.gov/browse/AB2D-6077

## 🛠 Changes

Addresses codesmells under the following severities (Note: some lines listed here may cover multiple smells):

Critical:
Add a nested comment to explain why JobSummaryEvent constructor is blank
Define a variable instead of duplicating string literal "OperationOutcome"
Define a constant instead of duplicating string literal "setValue"
Define a constant instead of duplicating string literal "Extension"
Define constants instead of duplicating string literals in BundleUtils
Define a constant instead of duplicating the literals "IncludeIdentifiers" and "mbi"
Remove Redundant Jump in PropertiesClientImpl

Major:
Refactor test case to reduce number of assertions in ExplanationOfBenefitTrimmerSTU3Test
Swap assertion expected and actual values across multiple files
Make non-static constant fields static
Add private constructor to public utility class FilterEob
Add private constructor to Utility class ExplanationOfBenefitTrimmerStu3
Add private constructor to Utility class ExplanationOfBenefitTrimmerR4
Add private constructor to Utility class ExplanationOfBenefitTrimmer
'description' hides the field declared on line 18. (removed line 34 as it was unnecessarily redundant)
Change the visibility of constructors in LoggableEvent to protected
Remove fields that hide other fields in LoggableEvent. (removed multiple unnecessarily redundant lines)
Change the visibility of constructor in SQSMessages to protected
Swap arguments in assertions to the correct order in SendSqsEventTest
Add private constructor to Utility class Versions
Add private constructor to Utility class EobLoadUtilities

Info:
Remove Public Modifier in PropertiesServiceMockTest
Remove Public Modifier in PropertiesClientTest
Remove Public Modifier in FilterTest
Remove Public Modifier in FilterOutByDateTest
Remove Public Modifier for ExplanationOfBenefitTrimmerSTU3Test
Remove Public Modifiers for Test cases in ExplanationOfBenefitTrimmerSTU3Test
Remove Public Modifier in ExplanationOfBenefitTrimmerR4Test

---------------------------------------------------------------------------------------------------------------

Add a nested comment to explain why JobSummaryEvent constructor is blank:
Screenshot 2024-03-27 at 10 41 47 AM

Define a variable instead of duplicating string literal "OperationOutcome":
Screenshot 2024-03-27 at 10 33 16 AM

Define a constant instead of duplicating string literal "setValue":
Screenshot 2024-03-27 at 10 20 21 AM

Define a constant instead of duplicating string literal "Extension":
Screenshot 2024-03-26 at 5 00 35 PM

Define constants instead of duplicating string literals in BundleUtils:
Screenshot 2024-03-26 at 4 58 28 PM

Define a constant instead of duplicating the literals "IncludeIdentifiers" and "mbi" 3 times:
Screenshot 2024-03-26 at 4 46 36 PM

Remove Public Modifier in PropertiesServiceMockTest: 
Screenshot 2024-03-25 at 11 53 35 AM

Remove Public Modifier in PropertiesClientTest:
Screenshot 2024-03-26 at 11 42 19 AM

Remove Public Modifier in FilterTest:
Screenshot 2024-03-26 at 11 44 37 AM

Remove Public Modifier in FilterOutByDateTest:
Screenshot 2024-03-26 at 11 46 29 AM

Remove Public Modifier for ExplanationOfBenefitTrimmerSTU3Test:
Screenshot 2024-03-26 at 11 48 25 AM

Removed Public Modifiers for Test cases in ExplanationOfBenefitTrimmerSTU3Test:
Screenshot 2024-03-26 at 11 53 00 AM
Screenshot 2024-03-26 at 11 53 14 AM
Screenshot 2024-03-26 at 11 53 24 AM

Remove Redundant Jump in PropertiesClientImpl:
Screenshot 2024-03-25 at 11 54 01 AM

Remove Public Modifier for ExplanationOfBenefitR4Test:
Screenshot 2024-04-02 at 9 49 46 AM

Add private constructor to public utility class FilterEob:
Screenshot 2024-04-17 at 11 20 50 AM

Add private constructor to utility class ExplanationOfBenefitTrimmerStu3:
Screenshot 2024-04-17 at 11 29 23 AM

'description' hides the field declared on line 18. (removed line 34 as it was unnecessarily redundant):
Screenshot 2024-04-19 at 9 45 22 AM

Change the visibility of constructors in LoggableEvent to protected:
Screenshot 2024-04-19 at 9 52 19 AM
Screenshot 2024-04-19 at 9 55 31 AM

Remove fields that hide other fields in LoggableEvent. (removed multiple unnecessarily redundant lines):
Screenshot 2024-04-19 at 10 00 08 AM

Change the visibility of constructor in SQSMessages to protected:
Screenshot 2024-04-19 at 10 07 24 AM

Swap arguments in assertions to the correct order in SendSqsEventTest:
Screenshot 2024-04-19 at 10 09 53 AM

Add private constructor to Utility class Versions (Added UtilityClass Annotation):
Screenshot 2024-04-19 at 10 16 23 AM

Add private constructor to Utility class EobLoadUtilities (Added UtilityClass Annotation):
Screenshot 2024-04-19 at 10 23 49 AM

## ✅ Acceptance Validation

Built Successfully on local environment:
Screenshot 2024-03-27 at 2 44 35 PM

TODO:
Redeploy all of AB2D with updated library versions after this change and test on lower environments.

## 🔒 Security Implications

- [ ] This PR adds a new software dependency or dependencies.
- [ ] This PR modifies or invalidates one or more of our security controls.
- [ ] This PR stores or transmits data that was not stored or transmitted before.
- [ ] This PR requires additional review of its security implications for other reasons.

If any security implications apply, add Jason Ashbaugh (GitHub username: StewGoin) as a reviewer and do not merge this PR without his approval.

### CODE REVIEW

**Comment by Sadibhatla** [comment]
https://sonarqube.cloud.cms.gov/project/issues?resolved=false&severities=BLOCKER&pullRequest=1327&id=ab2d-project

Looks like new critical/blocker came up from the changes made.
Please take a look  @Rwolfe-Nava

**Comment by Sadibhatla** [comment]
Also failed on the "duplicate lines" density precondition in SonarQube:
https://sonarqube.cloud.cms.gov/component_measures?id=ab2d-project&metric=new_duplicated_lines_density&pullRequest=1327&view=list

**Comment by Rwolfe-Nava** [comment]
> https://sonarqube.cloud.cms.gov/project/issues?resolved=false&severities=BLOCKER&pullRequest=1327&id=ab2d-project
> 
> Looks like new critical/blocker came up from the changes made. Please take a look @Rwolfe-Nava

This isn't actually new. It got flagged as new In my attempt to fix it, but its the same issue. I am not sure why sonarqube believes this code always returns the same value.. it shouldn't be the case 🤔.

Screenshot 2024-05-14 at 1 51 51 AM

**Review by Sadibhatla — APPROVED** [review]
merge to test code coverage in master branch

**Pull request merged**
